import { Manga, LibraryEntry } from "./types";

export const mockManga: Manga[] = [
  {
    id: "1",
    title: "Solo Leveling",
    coverImage: "https://picsum.photos/seed/soloLeveling/300/430",
    synopsis:
      "In a world where hunters battle monsters to protect humanity, Sung Jinwoo is the weakest of them all. A mysterious double dungeon changes his fate when he discovers a hidden quest system that allows him to level up infinitely.",
    genres: ["Action", "Adventure", "Fantasy"],
    themes: ["Level Up System", "Necromancy", "Dungeons", "Overpowered MC"],
    rating: 9.2,
    ratings: { anilist: 9.1, mal: 8.9, mangaupdates: 9.3 },
    status: "completed",
    chapters: 179,
    author: "Chugong",
    artist: "DUBU (Redice Studio)",
    year: 2018,
    isHot: true,
  },
  {
    id: "2",
    title: "Tower of God",
    coverImage: "https://picsum.photos/seed/towerofgod/300/430",
    synopsis:
      "Twenty-Fifth Bam opens the door to the Tower by sheer force of will, chasing after his only friend Rachel. Inside the Tower, he must climb through floors of deadly trials, forming alliances and uncovering dark secrets.",
    genres: ["Action", "Adventure", "Fantasy"],
    themes: ["Tower Climbing", "Betrayal", "Power Systems", "Politics"],
    rating: 8.8,
    ratings: { anilist: 8.7, mal: 8.6, webtoon: 9.0 },
    status: "ongoing",
    chapters: 600,
    author: "SIU",
    artist: "SIU",
    year: 2010,
    isHot: true,
  },
  {
    id: "3",
    title: "The Beginning After the End",
    coverImage: "https://picsum.photos/seed/tbate/300/430",
    synopsis:
      "King Grey — unrivaled in strength and fame — reincarnates into a world of magic and monsters. With memories of his past life, he strives to build genuine bonds and correct the mistakes of his lonely first existence.",
    genres: ["Action", "Fantasy", "Romance"],
    themes: ["Reincarnation", "Magic Academy", "Royalty", "Second Chance"],
    rating: 8.9,
    ratings: { anilist: 8.5, mal: 8.4, mangaupdates: 9.1 },
    status: "ongoing",
    chapters: 220,
    author: "TurtleMe",
    artist: "Fuyuki23",
    year: 2018,
    isAiPick: true,
  },
  {
    id: "4",
    title: "Omniscient Reader's Viewpoint",
    coverImage: "https://picsum.photos/seed/orv2024/300/430",
    synopsis:
      "Kim Dokja was the sole reader of the web novel 'Three Ways to Survive the Apocalypse.' When reality collapses into the novel's scenario, he is the only person alive who knows how the story ends.",
    genres: ["Action", "Drama", "Fantasy"],
    themes: ["Apocalypse", "Meta-Fiction", "Survival", "Chosen One"],
    rating: 9.5,
    ratings: { anilist: 9.4, mal: 9.0, mangaupdates: 9.6 },
    status: "ongoing",
    chapters: 180,
    author: "sing N song",
    artist: "Sleepy-C",
    year: 2020,
    isHot: true,
    isAiPick: true,
  },
  {
    id: "5",
    title: "Nano Machine",
    coverImage: "https://picsum.photos/seed/nanomachine5/300/430",
    synopsis:
      "A descendant from the future injects Cheon Yeo-Woon with nano machines, enhancing his body far beyond human limits. He must survive brutal clan politics while mastering martial arts at an unprecedented pace.",
    genres: ["Action", "Fantasy", "Martial Arts"],
    themes: ["Nano Technology", "Wuxia", "Clan Politics", "Overpowered MC"],
    rating: 8.7,
    ratings: { anilist: 8.4, mal: 8.3, mangaupdates: 8.8 },
    status: "ongoing",
    chapters: 190,
    author: "Han-Joong-Wol",
    artist: "Geumgang Bulgoe",
    year: 2019,
  },
  {
    id: "6",
    title: "Return of the Blossoming Blade",
    coverImage: "https://picsum.photos/seed/blossomblade6/300/430",
    synopsis:
      "Cheong Pung, disciple of the Heavenly Sword Pavilion, returns after his death to rewrite history. Armed with the memories of his past life, he must uncover the truth behind the great tragedy that destroyed everything.",
    genres: ["Action", "Fantasy", "Martial Arts"],
    themes: ["Wuxia", "Revenge", "Swordsmanship", "Time Travel"],
    rating: 8.6,
    ratings: { anilist: 8.3, mal: 8.2, mangaupdates: 8.7 },
    status: "ongoing",
    chapters: 155,
    author: "MH Namu",
    artist: "MH Namu",
    year: 2021,
    isAiPick: true,
  },
  {
    id: "7",
    title: "Overgeared",
    coverImage: "https://picsum.photos/seed/overgeared7/300/430",
    synopsis:
      "Shin Youngwoo, notorious for being the worst player in VR game Satisfy, stumbles upon a legendary blacksmithing class. He rises from the bottom to become the world's greatest craftsman and most feared king.",
    genres: ["Action", "Adventure", "Fantasy"],
    themes: ["Virtual Reality", "Blacksmithing", "Gaming", "Kingdom Building"],
    rating: 8.5,
    ratings: { anilist: 8.3, mal: 8.1, mangaupdates: 8.6 },
    status: "ongoing",
    chapters: 210,
    author: "Park Saenal",
    artist: "Moonkana",
    year: 2018,
  },
  {
    id: "8",
    title: "Eleceed",
    coverImage: "https://picsum.photos/seed/eleceed8/300/430",
    synopsis:
      "Jiwoo has cat-like agility and speed. When he rescues a fat cat harboring the consciousness of a powerful awakened master, an unlikely partnership forms to protect the innocent from supernatural threats.",
    genres: ["Action", "Comedy", "Fantasy"],
    themes: ["Cats", "Super Powers", "Mentor", "Modern Fantasy"],
    rating: 9.0,
    ratings: { anilist: 8.9, mal: 8.7, webtoon: 9.2 },
    status: "ongoing",
    chapters: 290,
    author: "Son Je-Ho",
    artist: "ZHENA",
    year: 2018,
    isAiPick: true,
  },
  {
    id: "9",
    title: "A Returner's Magic Should Be Special",
    coverImage: "https://picsum.photos/seed/returner9/300/430",
    synopsis:
      "Desir Herrman survives a Shadow World that killed everyone else, then is sent back 13 years. Knowing every catastrophe that's coming, he trains his classmates into a force capable of saving humanity.",
    genres: ["Action", "Fantasy", "School Life"],
    themes: ["Time Travel", "Magic Academy", "Strategy", "Party Dynamics"],
    rating: 8.4,
    ratings: { anilist: 8.2, mal: 8.0, mangaupdates: 8.5 },
    status: "completed",
    chapters: 190,
    author: "Wookjakga",
    artist: "Goldenhands",
    year: 2018,
  },
  {
    id: "10",
    title: "Reaper of the Drifting Moon",
    coverImage: "https://picsum.photos/seed/reapermoon10/300/430",
    synopsis:
      "Pyo Wol was kidnapped as a child and forced to survive impossible underground trials for years. He emerges as the world's most lethal assassin, walking the Jianghu world with cold efficiency and leaving silence in his wake.",
    genres: ["Action", "Mystery", "Martial Arts"],
    themes: ["Assassin", "Wuxia", "Dark", "Revenge"],
    rating: 8.9,
    ratings: { anilist: 8.6, mal: 8.5, mangaupdates: 9.0 },
    status: "ongoing",
    chapters: 165,
    author: "Woo-gak",
    artist: "Seokchae",
    year: 2022,
    isHot: true,
  },
  {
    id: "11",
    title: "God of Blackfield",
    coverImage: "https://picsum.photos/seed/blackfield11/300/430",
    synopsis:
      "The legendary Black Panther — France's deadliest special ops soldier — is reborn into the body of a bullied Korean high schooler. His lethal instincts and military genius do not transfer quietly.",
    genres: ["Action", "Drama", "Military"],
    themes: ["Military", "Reincarnation", "School", "Intelligence"],
    rating: 9.0,
    ratings: { anilist: 8.9, mal: 8.7, mangaupdates: 9.1 },
    status: "ongoing",
    chapters: 200,
    author: "Neul Boram",
    artist: "Seobeol",
    year: 2020,
    isHot: true,
  },
  {
    id: "12",
    title: "Memoir of the King of War",
    coverImage: "https://picsum.photos/seed/kingwar12/300/430",
    synopsis:
      "The greatest general in history reincarnates into the body of a decadent noble in an era of fragile peace. His battlefield genius simmers beneath a playboy facade as new conflicts approach on the horizon.",
    genres: ["Action", "Drama", "Historical"],
    themes: ["War", "Military Strategy", "Reincarnation", "Politics"],
    rating: 8.3,
    ratings: { anilist: 8.1, mal: 7.9, mangaupdates: 8.4 },
    status: "ongoing",
    chapters: 80,
    author: "Kim Sung-ho",
    artist: "Jung Ha-Rang",
    year: 2022,
    isAiPick: true,
  },
  {
    id: "13",
    title: "Skeleton Soldier Couldn't Protect the Dungeon",
    coverImage: "https://picsum.photos/seed/skeleton13/300/430",
    synopsis:
      "A skeleton soldier dies protecting his master and revives back in time. Through countless deaths and rebirths, the undead warrior grows stronger, bound by loyalty no one expects from bones and shadow.",
    genres: ["Action", "Fantasy", "Adventure"],
    themes: ["Undead", "Time Loop", "Growth", "Loyalty"],
    rating: 8.5,
    ratings: { anilist: 8.3, mal: 8.1, mangaupdates: 8.6 },
    status: "completed",
    chapters: 229,
    author: "SOSORI",
    artist: "SOSORI",
    year: 2018,
  },
  {
    id: "14",
    title: "The S-Classes That I Raised",
    coverImage: "https://picsum.photos/seed/sclasses14/300/430",
    synopsis:
      "Korea's only F-rank hunter possesses a unique skill: raising the potential rank of his pets. Sent back in time, he aims to raise all S-class hunters as loyal allies and avert the coming catastrophe.",
    genres: ["Action", "Fantasy", "Comedy"],
    themes: ["Time Travel", "Pets", "Hunters", "Taming"],
    rating: 8.7,
    ratings: { anilist: 8.5, mal: 8.4, mangaupdates: 8.8 },
    status: "completed",
    chapters: 160,
    author: "Gong Gong",
    artist: "Gong Gong",
    year: 2019,
    isAiPick: true,
  },
  {
    id: "15",
    title: "Kill the Hero",
    coverImage: "https://picsum.photos/seed/killhero15/300/430",
    synopsis:
      "The hero who was supposed to save the world planned all along to monopolize its power. Betrayed and killed by his own party, Kim Woo-Jin is sent back to the past to expose the 'hero' and claim his revenge.",
    genres: ["Action", "Fantasy", "Drama"],
    themes: ["Revenge", "Betrayal", "Anti-Hero", "Dungeons"],
    rating: 8.5,
    ratings: { anilist: 8.3, mal: 8.2, mangaupdates: 8.6 },
    status: "completed",
    chapters: 165,
    author: "Eunju Lim",
    artist: "Polkadot",
    year: 2019,
  },
  {
    id: "16",
    title: "Murim Login",
    coverImage: "https://picsum.photos/seed/murim16/300/430",
    synopsis:
      "An F-rank hunter discovers a mysterious Murim VR capsule inside a dungeon. Training as a swordsman within the virtual martial arts world, he brings back real power that transcends the game.",
    genres: ["Action", "Fantasy", "Martial Arts"],
    themes: ["Virtual Reality", "Murim", "Dual World", "Growth"],
    rating: 8.8,
    ratings: { anilist: 8.6, mal: 8.5, mangaupdates: 8.9 },
    status: "ongoing",
    chapters: 175,
    author: "Woo-jin Oh",
    artist: "Semi",
    year: 2020,
    isHot: true,
  },
  {
    id: "17",
    title: "Dungeon Reset",
    coverImage: "https://picsum.photos/seed/dunreset17/300/430",
    synopsis:
      "Dawoon gets trapped in a dungeon after a reset glitch leaves him behind. While the dungeon refreshes around him each cycle, he exploits the system's blind spots to craft weapons, build bases, and master the impossible.",
    genres: ["Action", "Adventure", "Comedy"],
    themes: ["Dungeons", "Crafting", "Solo", "System Exploitation"],
    rating: 8.6,
    ratings: { anilist: 8.4, mal: 8.3, mangaupdates: 8.7 },
    status: "ongoing",
    chapters: 210,
    author: "Arang",
    artist: "Arang",
    year: 2019,
  },
  {
    id: "18",
    title: "Chronicles of the Martial God's Return",
    coverImage: "https://picsum.photos/seed/martialgod18/300/430",
    synopsis:
      "The Martial God, who achieved the pinnacle of cultivation, was betrayed and destroyed by the Six Sects. Reincarnating into his younger self, he holds every memory of reaching godhood — and intends to use it.",
    genres: ["Action", "Fantasy", "Martial Arts"],
    themes: ["Reincarnation", "Cultivation", "Revenge", "God-Level MC"],
    rating: 8.6,
    ratings: { anilist: 8.4, mal: 8.2, mangaupdates: 8.7 },
    status: "ongoing",
    chapters: 110,
    author: "Hyeon Oh",
    artist: "Man-ga Pro",
    year: 2021,
  },
  {
    id: "19",
    title: "The Lone Necromancer",
    coverImage: "https://picsum.photos/seed/necro19/300/430",
    synopsis:
      "When monster gates tear reality open, Sung-woo awakens as a Necromancer — a class no one wants. Commanding an ever-growing army of undead, he will become the world's most feared and mightiest summoner.",
    genres: ["Action", "Fantasy", "Adventure"],
    themes: ["Necromancy", "Summoning", "Undead Army", "Dungeons"],
    rating: 8.4,
    ratings: { anilist: 8.2, mal: 8.0, mangaupdates: 8.5 },
    status: "ongoing",
    chapters: 100,
    author: "Park Kyunggeun",
    artist: "Gilbut",
    year: 2021,
  },
  {
    id: "20",
    title: "Villain to Kill",
    coverImage: "https://picsum.photos/seed/villaintokill20/300/430",
    synopsis:
      "A hero's soul transfers into the body of a ruthless villain. Confused but calculating, he must survive in the skin of someone everyone wants dead — while uncovering the conspiracy that put him there.",
    genres: ["Action", "Fantasy", "Thriller"],
    themes: ["Anti-Hero", "Body Swap", "Villain Protagonist", "Conspiracy"],
    rating: 8.7,
    ratings: { anilist: 8.5, mal: 8.3, mangaupdates: 8.8 },
    status: "ongoing",
    chapters: 130,
    author: "Bae Soo Hyeon",
    artist: "RAMAZAN KAYACETIN",
    year: 2021,
    isAiPick: true,
  },
];

export const trendingManga = mockManga
  .filter((m) => m.isHot || m.rating >= 9.0)
  .slice(0, 6);

export const topRatedManga = [...mockManga]
  .sort((a, b) => b.rating - a.rating)
  .slice(0, 12);

export const aiPicksManga = mockManga.filter((m) => m.isAiPick).slice(0, 8);

export const recentlyUpdated = mockManga.slice(0, 12);

export const mockLibrary: LibraryEntry[] = [
  {
    mangaId: "4",
    manga: mockManga[3],
    status: "reading",
    progress: 98,
    updatedAt: new Date("2026-05-30"),
  },
  {
    mangaId: "2",
    manga: mockManga[1],
    status: "reading",
    progress: 320,
    updatedAt: new Date("2026-05-28"),
  },
  {
    mangaId: "11",
    manga: mockManga[10],
    status: "reading",
    progress: 67,
    updatedAt: new Date("2026-05-25"),
  },
  {
    mangaId: "1",
    manga: mockManga[0],
    status: "completed",
    progress: 179,
    updatedAt: new Date("2026-04-15"),
  },
  {
    mangaId: "9",
    manga: mockManga[8],
    status: "completed",
    progress: 190,
    updatedAt: new Date("2026-03-20"),
  },
  {
    mangaId: "13",
    manga: mockManga[12],
    status: "completed",
    progress: 229,
    updatedAt: new Date("2026-02-10"),
  },
  {
    mangaId: "15",
    manga: mockManga[14],
    status: "completed",
    progress: 165,
    updatedAt: new Date("2026-01-30"),
  },
  {
    mangaId: "8",
    manga: mockManga[7],
    status: "on-hold",
    progress: 145,
    updatedAt: new Date("2026-01-15"),
  },
  {
    mangaId: "5",
    manga: mockManga[4],
    status: "plan-to-read",
    progress: 0,
    updatedAt: new Date("2026-05-01"),
  },
  {
    mangaId: "6",
    manga: mockManga[5],
    status: "plan-to-read",
    progress: 0,
    updatedAt: new Date("2026-05-10"),
  },
  {
    mangaId: "7",
    manga: mockManga[6],
    status: "dropped",
    progress: 30,
    updatedAt: new Date("2025-12-01"),
  },
];
